# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --frozen-lockfile
      - name: Check uncommitted changes
        run: |
          yarn dev &
          sleep 30
          npm run graphql:schema:generate
          clean=$(git status | grep "nothing to commit")
          if [ -z "$clean" ]; then
              echo There are uncommitted changes.
              exit 1
          else
              echo Branch is clean.
          fi
      - run: npm run lint
      - run: npm test
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          install-command: yarn install
          build: yarn run build
          start: yarn start
          wait-on: 'http://localhost:3000'